# Site
title:              Ramiro V S Júnior
bio:                'Mestrando em Cognição, Tecnologias e Instituições pela Universidade Federal Rural do Semi-Árido (UFERSA). 
                    Graduação em Ciência da Computação pela UFERSA (2017). Atuou como bolsista de iniciação científica (PIVIC) no 
                    Núcleo Tecnológico de Engenharia de Software - NTES - UFERSA. Tem experiência na área de Ciência da Computação. 
                    Possui curso técnico em Tecnologia da Informação com Ênfase em Redes de Computadores pelo Instituto Metrópole Digital - 
                    UFRN / UFERSA (2014).'
description:        "Blog para informações relacionadas à Ciência da Computação, Ciência de Dados e Segurança Pública."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://ramirovsjunior.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   ramirovsjunior

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            ramirovsjunior
facebook:           ramirovsjunior
github-url:         ramirovsjunior
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          ramirovsjunior
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
